services:
  vbot:
    build: .
    environment:
      APP_ID: $APP_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      DOWNLOAD_DIR: $DOWNLOAD_DIR
      ENCODE_DIR: $ENCODE_DIR
      SUDO_USERS: $SUDO_USERS
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
    command: python3 bot.py
